export enum ActionType {
  GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS',
  GET_ALBUMS_LOADING = 'GET_ALBUMS_LOADING',
  GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR',

  GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_LOADING = 'GET_PHOTOS_LOADING',
  GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR',
};